[package]
name = "evm_rpc"
version = "0.1.0"
description = "Interact with EVM blockchains from the Internet Computer."
authors = ["DFINITY Foundation"]
readme = "README.md"
edition = "2021"

[profile.release]
debug = false
lto = true
opt-level = 'z'

[dependencies]
candid = { workspace = true }
ic-canister-log = { workspace = true }
ic-canisters-http-types = { workspace = true }
ic-nervous-system-common = { workspace = true }
ic-metrics-encoder = { workspace = true }
ic-stable-structures = { workspace = true }
ic-certified-map = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-eth = { workspace = true }
# TODO: https://github.com/internet-computer-protocol/ic-eth-rpc/issues/74
cketh-common = { git = "https://github.com/rvanasa/ic", branch = "evm-rpc-canister", package = "ic-cketh-minter" }
num = "0.4"
num-traits = "0.2"
num-derive = "0.4"
serde = "1.0"
serde_json = "1.0"
url = "2.4"
async-trait = "0.1"
hex = "0.4"

[dev-dependencies]
# assert_matches = "1.5.0"
# ethers-core = "2.0.8"
ic-base-types = { path = "../../../types/base_types" }
ic-config = { path = "../../../config" }
ic-crypto-test-utils-reproducible-rng = { path = "../../../crypto/test_utils/reproducible_rng" }
ic-icrc1-ledger = { path = "../../../rosetta-api/icrc1/ledger" }
ic-state-machine-tests = { path = "../../../state_machine_tests" }
ic-test-utilities-load-wasm = { path = "../../../test_utilities/load_wasm" }
# maplit = "1"
# proptest = "1.0"
# rand = "0.8"
# scraper = "0.17.1"

[workspace.dependencies]
candid = { version = "0.9", features = ["parser"] }
ic-canister-log = { git = "https://github.com/dfinity/ic", rev = "release-2023-09-27_23-01" }
ic-canisters-http-types = { git = "https://github.com/dfinity/ic", rev = "release-2023-09-27_23-01" }
ic-nervous-system-common = { git = "https://github.com/dfinity/ic", rev = "release-2023-09-27_23-01" }
ic-metrics-encoder = "1.1"
ic-stable-structures = "0.5"
ic-certified-map = "0.4"
ic-cdk = "0.10"
ic-cdk-macros = "0.7"
ic-cdk-bindgen = "0.1"
ic-eth = { path = "lib/rust" }

[patch.crates-io]
wasm-bindgen = { git = "https://github.com/rvanasa/wasm-bindgen", rev = "d50634da14c5bd031edd4f81ab4bf345cda2bc39" }

[workspace]
members = ["lib/rust", "e2e/rust"]
